# Generated by Django 5.1.6 on 2025-05-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kids_quest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
